
services:
  postgres:
    image: postgres:16-alpine
    container_name: chatbox-v2-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chatbox_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: chatbox-v2-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_v2:/data/db

volumes:
  postgres_data_v2:
  mongo_data_v2: